spring:
  datasource:
    master:
      # 驱动类
      driver-class-name: com.mysql.jdbc.Driver
      # 主数据库服务器用户名
      username: root
      # 主数据库服务器密码
      password: 123456
      # 主数据库服务器用户名，到时候更换自己的ip端口
      jdbc-url: jdbc:mysql://localhost:3307/test?characterEncoding=utf-8&allowPublicKeyRetrieval=true
      # 从数据库服务器配置
    slave:
      # 从数据库服务器用户名
      username: root
      # 从数据库服务器密码
      password: 123456
      # 从数据库服务器url,到时候更换自己的ip端口
      jdbc-url: jdbc:mysql://localhost:3308/test?characterEncoding=utf-8&allowPublicKeyRetrieval=true


logging:
  level:
    com.readwite.application: debug